# Generated by Django 4.2.4 on 2023-08-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj_cpf', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('atividade_economica_profissao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaCorte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaExtrusao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaImpressao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('tratamento', models.CharField(max_length=100)),
                ('tipoMaterial', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('acabamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_1', models.CharField(max_length=50)),
                ('cor_2', models.CharField(max_length=50)),
                ('cor_3', models.CharField(max_length=50)),
                ('cor_4', models.CharField(max_length=50)),
                ('cor_5', models.CharField(max_length=50)),
                ('cor_6', models.CharField(max_length=50)),
                ('cor_7', models.CharField(max_length=50)),
                ('cor_8', models.CharField(max_length=50)),
                ('cor_9', models.CharField(max_length=50)),
                ('cor_10', models.CharField(max_length=50)),
                ('cor_11', models.CharField(max_length=50)),
                ('cor_12', models.CharField(max_length=50)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.produto'),
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente_1', models.CharField(max_length=100)),
                ('ingrediente_2', models.CharField(max_length=100)),
                ('ingrediente_3', models.CharField(max_length=100)),
                ('ingrediente_4', models.CharField(max_length=100)),
                ('ingrediente_5', models.CharField(max_length=100)),
                ('ingrediente_6', models.CharField(max_length=100)),
                ('ingrediente_7', models.CharField(max_length=100)),
                ('ingrediente_8', models.CharField(max_length=100)),
                ('ingrediente_9', models.CharField(max_length=100)),
                ('ingrediente_10', models.CharField(max_length=100)),
                ('ingrediente_11', models.CharField(max_length=100)),
                ('ingrediente_12', models.CharField(max_length=100)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('data', models.DateField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.operador')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
                ('printing_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.maquinaimpressao')),
            ],
        ),
        migrations.CreateModel(
            name='Extrusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('data', models.DateField()),
                ('maquina_extrusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.maquinaextrusao')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.operador')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('data', models.DateField()),
                ('cutting_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.maquinacorte')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.operador')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
    ]
