# Generated by Django 4.2.4 on 2023-08-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_rename_cutting_machine_corte_maquina_corte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TintaOrdemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.tinta')),
                ('ordemservico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteOrdemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ingredientes')),
                ('ordemservico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
    ]
