# Generated by Django 4.2.4 on 2023-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_tintaordemservico_ingredienteordemservico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tintaordemservico',
            old_name='ingrediente_id',
            new_name='tinta_id',
        ),
        migrations.RemoveField(
            model_name='ingredientes',
            name='ordem_servico',
        ),
        migrations.RemoveField(
            model_name='tinta',
            name='ordem_servico',
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tinta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
