# Generated by Django 4.2.4 on 2023-08-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0004_rename_ingrediente_id_tintaordemservico_tinta_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredienteordemservico',
            old_name='ingrediente_id',
            new_name='ingrediente',
        ),
        migrations.RenameField(
            model_name='ingredienteordemservico',
            old_name='ordemservico_id',
            new_name='ordemservico',
        ),
        migrations.RenameField(
            model_name='tintaordemservico',
            old_name='ordemservico_id',
            new_name='ordemservico',
        ),
        migrations.RenameField(
            model_name='tintaordemservico',
            old_name='tinta_id',
            new_name='tinta',
        ),
    ]
