# Generated by Django 4.2.4 on 2023-08-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0005_rename_ingrediente_id_ingredienteordemservico_ingrediente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='tipoMaterial',
            new_name='tipo_material',
        ),
    ]
