# Generated by Django 4.2.4 on 2023-08-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0007_rename_ingrediente_1_ingredientes_ingrediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('hora_alteracao', models.DateTimeField()),
                ('data_alteracao', models.DateField()),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.operador')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
    ]
