# Generated by Django 4.2.4 on 2023-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0008_statusservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienteordemservico',
            name='qtde',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tintaordemservico',
            name='qtde',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
