# Generated by Django 4.2.4 on 2023-08-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0009_ingredienteordemservico_qtde_tintaordemservico_qtde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='status',
        ),
    ]
