# Generated by Django 4.2.4 on 2023-08-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0010_remove_ordemservico_data_remove_ordemservico_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tratamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.material'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.tratamento'),
        ),
    ]
