# Generated by Django 4.2.4 on 2023-08-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0011_material_tratamento_alter_ordemservico_tipo_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoImpressao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=10)),
                ('qtde', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('item_produzido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.impressao')),
                ('ordemservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoExtrusao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=10)),
                ('qtde', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('item_produzido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.extrusao')),
                ('ordemservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCorte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=10)),
                ('qtde', models.CharField(max_length=10)),
                ('peso', models.CharField(max_length=10)),
                ('item_produzido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.corte')),
                ('ordemservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.ordemservico')),
            ],
        ),
    ]
