# Generated by Django 4.2.4 on 2023-08-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0012_produtoimpressao_produtoextrusao_produtocorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acabamento_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CorProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cor_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='material_produto',
        ),
        migrations.RenameField(
            model_name='tratamento',
            old_name='tratamento',
            new_name='tratamento_produto',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_material',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tratamento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='acabamento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='material',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='material_produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.material'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tratamento_produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.tratamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='acabamento_produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.acabamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='cor_produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.corproduto'),
            preserve_default=False,
        ),
    ]
