# Generated by Django 4.2.4 on 2023-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0013_acabamento_corproduto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
