# Generated by Django 4.2.4 on 2023-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0014_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(default='2023-08-26'),
            preserve_default=False,
        ),
    ]
