# Generated by Django 4.2.4 on 2023-08-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0015_ordemservico_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data',
            new_name='data_inicio',
        ),
    ]
