# Generated by Django 4.2.4 on 2023-08-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0017_remove_ordemservico_produto_produto_ordem_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusservico',
            name='data_alteracao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusservico',
            name='hora_alteracao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
