# Generated by Django 4.2.4 on 2023-08-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0018_alter_ordemservico_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienteordemservico',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gerenciamento.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredienteordemservico',
            name='qtde',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_ordem_servico', to='gerenciamento.ordemservico'),
        ),
    ]
