# Generated by Django 4.2.4 on 2023-08-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0019_ingredienteordemservico_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteordemservico',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_ordem_servico', to='gerenciamento.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='gerenciamento.ordemservico'),
        ),
    ]
