# Generated by Django 4.2.4 on 2023-08-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0020_alter_ingredienteordemservico_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteordemservico',
            name='qtde',
            field=models.FloatField(),
        ),
    ]
