# Generated by Django 4.2.4 on 2023-08-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0022_rename_data_extrusao_data_fim_extrusao_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrusao',
            name='ordem_servico',
        ),
    ]
