# Generated by Django 4.2.4 on 2023-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0023_remove_extrusao_ordem_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusao',
            name='hora_fim',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='extrusao',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
