# Generated by Django 4.2.4 on 2023-08-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0025_extrusao_desperdicio_extrusao_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrusao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrusao',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
